INSERT INTO countries (code, code_alpha3, name, native_name, phone_code, currency_code, flag_emoji) VALUES
('US', 'USA', 'United States', 'United States', '+1', 'USD', '🇺🇸'),
('IN', 'IND', 'India', 'भारत', '+91', 'INR', '🇮🇳'),
('GB', 'GBR', 'United Kingdom', 'United Kingdom', '+44', 'GBP', '🇬🇧'),
('CA', 'CAN', 'Canada', 'Canada', '+1', 'CAD', '🇨🇦'),
('AU', 'AUS', 'Australia', 'Australia', '+61', 'AUD', '🇦🇺'),
('DE', 'DEU', 'Germany', 'Deutschland', '+49', 'EUR', '🇩🇪'),
('FR', 'FRA', 'France', 'France', '+33', 'EUR', '🇫🇷'),
('JP', 'JPN', 'Japan', '日本', '+81', 'JPY', '🇯🇵'),
('CN', 'CHN', 'China', '中国', '+86', 'CNY', '🇨🇳'),
('BR', 'BRA', 'Brazil', 'Brasil', '+55', 'BRL', '🇧🇷'),
('MX', 'MEX', 'Mexico', 'México', '+52', 'MXN', '🇲🇽'),
('ES', 'ESP', 'Spain', 'España', '+34', 'EUR', '🇪🇸'),
('IT', 'ITA', 'Italy', 'Italia', '+39', 'EUR', '🇮🇹'),
('RU', 'RUS', 'Russia', 'Россия', '+7', 'RUB', '🇷🇺'),
('KR', 'KOR', 'South Korea', '대한민국', '+82', 'KRW', '🇰🇷'),
('NL', 'NLD', 'Netherlands', 'Nederland', '+31', 'EUR', '🇳🇱'),
('SE', 'SWE', 'Sweden', 'Sverige', '+46', 'SEK', '🇸🇪'),
('NO', 'NOR', 'Norway', 'Norge', '+47', 'NOK', '🇳🇴'),
('DK', 'DNK', 'Denmark', 'Danmark', '+45', 'DKK', '🇩🇰'),
('FI', 'FIN', 'Finland', 'Suomi', '+358', 'EUR', '🇫🇮'),
('PL', 'POL', 'Poland', 'Polska', '+48', 'PLN', '🇵🇱'),
('TR', 'TUR', 'Turkey', 'Türkiye', '+90', 'TRY', '🇹🇷'),
('SA', 'SAU', 'Saudi Arabia', 'السعودية', '+966', 'SAR', '🇸🇦'),
('AE', 'ARE', 'United Arab Emirates', 'الإمارات', '+971', 'AED', '🇦🇪'),
('SG', 'SGP', 'Singapore', 'Singapore', '+65', 'SGD', '🇸🇬'),
('MY', 'MYS', 'Malaysia', 'Malaysia', '+60', 'MYR', '🇲🇾'),
('TH', 'THA', 'Thailand', 'ประเทศไทย', '+66', 'THB', '🇹🇭'),
('ID', 'IDN', 'Indonesia', 'Indonesia', '+62', 'IDR', '🇮🇩'),
('PH', 'PHL', 'Philippines', 'Pilipinas', '+63', 'PHP', '🇵🇭'),
('VN', 'VNM', 'Vietnam', 'Việt Nam', '+84', 'VND', '🇻🇳'),
('PK', 'PAK', 'Pakistan', 'پاکستان', '+92', 'PKR', '🇵🇰'),
('BD', 'BGD', 'Bangladesh', 'বাংলাদেশ', '+880', 'BDT', '🇧🇩'),
('NG', 'NGA', 'Nigeria', 'Nigeria', '+234', 'NGN', '🇳🇬'),
('ZA', 'ZAF', 'South Africa', 'South Africa', '+27', 'ZAR', '🇿🇦'),
('EG', 'EGY', 'Egypt', 'مصر', '+20', 'EGP', '🇪🇬'),
('AR', 'ARG', 'Argentina', 'Argentina', '+54', 'ARS', '🇦🇷'),
('CL', 'CHL', 'Chile', 'Chile', '+56', 'CLP', '🇨🇱'),
('CO', 'COL', 'Colombia', 'Colombia', '+57', 'COP', '🇨🇴'),
('PE', 'PER', 'Peru', 'Perú', '+51', 'PEN', '🇵🇪'),
('NZ', 'NZL', 'New Zealand', 'New Zealand', '+64', 'NZD', '🇳🇿'),
('IE', 'IRL', 'Ireland', 'Ireland', '+353', 'EUR', '🇮🇪'),
('CH', 'CHE', 'Switzerland', 'Schweiz', '+41', 'CHF', '🇨🇭'),
('AT', 'AUT', 'Austria', 'Österreich', '+43', 'EUR', '🇦🇹'),
('BE', 'BEL', 'Belgium', 'België', '+32', 'EUR', '🇧🇪'),
('PT', 'PRT', 'Portugal', 'Portugal', '+351', 'EUR', '🇵🇹'),
('GR', 'GRC', 'Greece', 'Ελλάδα', '+30', 'EUR', '🇬🇷'),
('CZ', 'CZE', 'Czech Republic', 'Česko', '+420', 'CZK', '🇨🇿'),
('IL', 'ISR', 'Israel', 'ישראל', '+972', 'ILS', '🇮🇱'),
('HK', 'HKG', 'Hong Kong', '香港', '+852', 'HKD', '🇭🇰'),
('TW', 'TWN', 'Taiwan', '台灣', '+886', 'TWD', '🇹🇼')
ON CONFLICT (code) DO NOTHING;
