('ASP.NET', 'aspnet', 'Framework', '.NET web framework'),
('Flutter', 'flutter', 'Framework', 'Cross-platform mobile framework'),
('React Native', 'react-native', 'Framework', 'Mobile app framework using React'),

-- Databases
('MySQL', 'mysql', 'Database', 'Popular relational database'),
('PostgreSQL', 'postgresql', 'Database', 'Advanced open-source RDBMS'),
('MongoDB', 'mongodb', 'Database', 'NoSQL document database'),
('Redis', 'redis', 'Database', 'In-memory data structure store'),
('SQLite', 'sqlite', 'Database', 'Lightweight embedded database'),
('Oracle Database', 'oracle-db', 'Database', 'Enterprise relational database'),
('Microsoft SQL Server', 'mssql', 'Database', 'Microsoft relational database'),
('Cassandra', 'cassandra', 'Database', 'Distributed NoSQL database'),
('DynamoDB', 'dynamodb', 'Database', 'AWS NoSQL database service'),
('Elasticsearch', 'elasticsearch', 'Database', 'Search and analytics engine'),
('Firebase', 'firebase', 'Database', 'Google mobile/web platform'),

-- Cloud & DevOps
('AWS', 'aws', 'Cloud/DevOps', 'Amazon Web Services cloud platform'),
('Azure', 'azure', 'Cloud/DevOps', 'Microsoft cloud platform'),
('Google Cloud', 'google-cloud', 'Cloud/DevOps', 'Google Cloud Platform'),
('Docker', 'docker', 'Cloud/DevOps', 'Containerization platform'),
('Kubernetes', 'kubernetes', 'Cloud/DevOps', 'Container orchestration system'),
('Jenkins', 'jenkins', 'Cloud/DevOps', 'Automation server for CI/CD'),
('GitLab CI', 'gitlab-ci', 'Cloud/DevOps', 'GitLab continuous integration'),
('GitHub Actions', 'github-actions', 'Cloud/DevOps', 'GitHub automation workflows'),
('Terraform', 'terraform', 'Cloud/DevOps', 'Infrastructure as code tool'),
('Ansible', 'ansible', 'Cloud/DevOps', 'IT automation platform'),
('Git', 'git', 'Cloud/DevOps', 'Version control system'),
('Linux', 'linux', 'Cloud/DevOps', 'Unix-like operating system'),
('Nginx', 'nginx', 'Cloud/DevOps', 'Web server and reverse proxy'),

-- Design Tools
('Figma', 'figma', 'Design Tool', 'Collaborative design platform'),
('Adobe Photoshop', 'photoshop', 'Design Tool', 'Image editing software'),
('Adobe Illustrator', 'illustrator', 'Design Tool', 'Vector graphics editor'),
('Adobe XD', 'adobe-xd', 'Design Tool', 'UI/UX design tool'),
('Sketch', 'sketch', 'Design Tool', 'Digital design toolkit'),
('InVision', 'invision', 'Design Tool', 'Digital product design platform'),
('After Effects', 'after-effects', 'Design Tool', 'Motion graphics software'),
('Premiere Pro', 'premiere-pro', 'Design Tool', 'Video editing software'),
('Blender', 'blender', 'Design Tool', '3D creation suite'),
('AutoCAD', 'autocad', 'Design Tool', 'CAD software'),

-- Soft Skills
('Leadership', 'leadership', 'Soft Skill', 'Ability to lead and inspire teams'),
('Communication', 'communication', 'Soft Skill', 'Effective verbal and written communication'),
('Problem Solving', 'problem-solving', 'Soft Skill', 'Analytical thinking and solutions'),
('Teamwork', 'teamwork', 'Soft Skill', 'Collaborative work abilities'),
('Time Management', 'time-management', 'Soft Skill', 'Efficient task prioritization'),
('Critical Thinking', 'critical-thinking', 'Soft Skill', 'Logical analysis and reasoning'),
('Creativity', 'creativity', 'Soft Skill', 'Innovative and original thinking'),
('Adaptability', 'adaptability', 'Soft Skill', 'Flexibility in changing environments'),
('Project Management', 'project-management', 'Soft Skill', 'Planning and executing projects'),
('Public Speaking', 'public-speaking', 'Soft Skill', 'Presenting to audiences'),
('Negotiation', 'negotiation', 'Soft Skill', 'Reaching agreements effectively'),
('Emotional Intelligence', 'emotional-intelligence', 'Soft Skill', 'Understanding and managing emotions'),

-- Marketing & Analytics
('Google Analytics', 'google-analytics', 'Marketing Tool', 'Web analytics service'),
('SEO', 'seo', 'Marketing Tool', 'Search engine optimization'),
('SEM', 'sem', 'Marketing Tool', 'Search engine marketing'),
('Content Marketing', 'content-marketing', 'Marketing Tool', 'Content strategy and creation'),
('Social Media Marketing', 'social-media-marketing', 'Marketing Tool', 'Marketing via social platforms'),
('Email Marketing', 'email-marketing', 'Marketing Tool', 'Email campaign management'),
('HubSpot', 'hubspot', 'Marketing Tool', 'Inbound marketing platform'),
('Mailchimp', 'mailchimp', 'Marketing Tool', 'Email marketing service'),
('Hootsuite', 'hootsuite', 'Marketing Tool', 'Social media management'),
('Google Ads', 'google-ads', 'Marketing Tool', 'Online advertising platform'),
('Facebook Ads', 'facebook-ads', 'Marketing Tool', 'Facebook advertising'),

-- Business & Productivity
('Microsoft Excel', 'excel', 'Business Tool', 'Spreadsheet software'),
('Microsoft PowerPoint', 'powerpoint', 'Business Tool', 'Presentation software'),
('Salesforce', 'salesforce', 'Business Tool', 'CRM platform'),
('Jira', 'jira', 'Business Tool', 'Project tracking software'),
('Trello', 'trello', 'Business Tool', 'Project management tool'),
('Asana', 'asana', 'Business Tool', 'Work management platform'),
('Slack', 'slack', 'Business Tool', 'Team communication platform'),
('Zoom', 'zoom', 'Business Tool', 'Video conferencing software'),
('Tableau', 'tableau', 'Business Tool', 'Data visualization software'),
('Power BI', 'power-bi', 'Business Tool', 'Business analytics service'),
('SAP', 'sap', 'Business Tool', 'Enterprise resource planning'),
('QuickBooks', 'quickbooks', 'Business Tool', 'Accounting software')
ON CONFLICT (slug) DO NOTHING;