scalar UUID

type Country {
  id: UUID!
  code: String!
  codeAlpha3: String!
  name: String!
  nativeName: String
  phoneCode: String
  currencyCode: String
  flagEmoji: String
  isActive: Boolean!
  createdAt: String
}

extend type Query {
  Listcountries: [Country!]!
  GetCountryById(id: UUID!): Country
}


input CreateCountryInput {
  code: String!
  codeAlpha3: String!
  name: String!
  nativeName: String
  phoneCode: String
  currencyCode: String
  flagEmoji: String
  isActive: Boolean
}

input UpdateCountryInput {
  code: String
  codeAlpha3: String
  name: String
  nativeName: String
  phoneCode: String
  currencyCode: String
  flagEmoji: String
  isActive: Boolean
}

extend type Mutation {
  createCountry(input: CreateCountryInput!): Country!
  updateCountry(id: UUID!, input: UpdateCountryInput!): Country!
  deleteCountry(id: UUID!): Boolean!
}
