package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	"github.com/manojnegi/gql/graph/model"
)

// Listcountries is the resolver for the Listcountries field.
func (r *queryResolver) Listcountries(ctx context.Context) ([]*model.Country, error) {
	countries, err := r.queries.ListCountries(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Country, len(countries))
	for i, country := range countries {
		result[i] = &model.Country{
			ID:           PgUUIDToUUID(country.ID),
			Code:         country.Code,
			CodeAlpha3:   country.CodeAlpha3,
			Name:         country.Name,
			NativeName:   PgTextPtr(country.NativeName),
			PhoneCode:    PgTextPtr(country.PhoneCode),
			CurrencyCode: PgTextPtr(country.CurrencyCode),
			FlagEmoji:    PgTextPtr(country.FlagEmoji),
			IsActive:     country.IsActive.Bool,
			CreatedAt:    PgTimestampPtrString(country.CreatedAt),
		}
	}
	return result, nil
}
