package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"errors"
	"fmt"

	pgx "github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/manojnegi/gql/db"
	"github.com/manojnegi/gql/graph/model"
	"golang.org/x/crypto/bcrypt"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	// Combine first name and last name into full name
	fullName := input.Fname + " " + input.Lname

	// Generate username from email (take part before @)
	username := input.Email
	if idx := len(input.Email); idx > 0 {
		for i := 0; i < len(input.Email); i++ {
			if input.Email[i] == '@' {
				username = input.Email[:i]
				break
			}
		}
	}

	// Use sqlc to create user (ID is auto-generated by database)
	dbUser, err := r.queries.CreateUser(ctx, db.CreateUserParams{
		FullName:     pgtype.Text{String: fullName, Valid: true},
		Username:     username,
		Email:        pgtype.Text{String: input.Email, Valid: true},
		PasswordHash: pgtype.Text{String: "", Valid: false}, // No password for createUser
	})

	if err != nil {
		return nil, fmt.Errorf("failed to create user: %w", err)
	}

	// Convert db.CreateUserRow to model.User
	fullNameStr := ""
	if dbUser.FullName.Valid {
		fullNameStr = dbUser.FullName.String
	}
	emailStr := ""
	if dbUser.Email.Valid {
		emailStr = dbUser.Email.String
	}

	return &model.User{
		ID:       fmt.Sprintf("%d", dbUser.ID), // Convert int64 to string
		FullName: &fullNameStr,
		Email:    &emailStr,
	}, nil
}

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, input model.SignUp) (*model.User, error) {
	// Check if email already exists
	emailText := pgtype.Text{String: input.Email, Valid: true}
	_, err := r.queries.GetUserByEmail(ctx, emailText)
	if err == nil {
		return nil, fmt.Errorf("email already exists")
	}
	if !errors.Is(err, pgx.ErrNoRows) {
		// Some other database error occurred
		return nil, fmt.Errorf("failed to check email: %w", err)
	}

	// Hash the password
	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(input.Password), bcrypt.DefaultCost)
	if err != nil {
		return nil, fmt.Errorf("failed to hash password: %w", err)
	}

	// Generate username from fullName (lowercase, replace spaces with underscores)
	username := input.FullName
	// Simple username generation: lowercase and replace spaces
	usernameBytes := []byte(username)
	for i := range usernameBytes {
		if usernameBytes[i] == ' ' {
			usernameBytes[i] = '_'
		} else if usernameBytes[i] >= 'A' && usernameBytes[i] <= 'Z' {
			usernameBytes[i] = usernameBytes[i] + 32 // Convert to lowercase
		}
	}
	username = string(usernameBytes)
	// If username is too long or empty, use email prefix
	if len(username) == 0 || len(username) > 100 {
		username = input.Email
		for i := 0; i < len(username); i++ {
			if username[i] == '@' {
				username = username[:i]
				break
			}
		}
	}

	// Use sqlc to sign up user (database auto-generates ID)
	dbUser, err := r.queries.SignUpUser(ctx, db.SignUpUserParams{
		FullName:     pgtype.Text{String: input.FullName, Valid: true},
		Username:     username,
		Email:        emailText,
		PasswordHash: pgtype.Text{String: string(hashedPassword), Valid: true},
	})

	if err != nil {
		return nil, fmt.Errorf("failed to sign up user: %w", err)
	}

	// Convert db.SignUpUserRow to model.User
	fullNameStr := ""
	if dbUser.FullName.Valid {
		fullNameStr = dbUser.FullName.String
	}
	emailStr := ""
	if dbUser.Email.Valid {
		emailStr = dbUser.Email.String
	}

	return &model.User{
		ID:       fmt.Sprintf("%d", dbUser.ID), // Convert int64 to string for GraphQL ID
		FullName: &fullNameStr,
		Email:    &emailStr,
	}, nil
}

// SignIn is the resolver for the signIn field.
func (r *mutationResolver) SignIn(ctx context.Context, input model.SignIn) (*model.User, error) {
	// Get user by email
	emailText := pgtype.Text{String: input.Email, Valid: true}
	dbUser, err := r.queries.GetUserByEmail(ctx, emailText)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("invalid email or password")
		}
		return nil, fmt.Errorf("failed to get user: %w", err)
	}

	// Check if password hash exists
	if !dbUser.PasswordHash.Valid || dbUser.PasswordHash.String == "" {
		return nil, fmt.Errorf("invalid email or password")
	}

	// Compare password with hash
	err = bcrypt.CompareHashAndPassword([]byte(dbUser.PasswordHash.String), []byte(input.Password))
	if err != nil {
		return nil, fmt.Errorf("invalid email or password")
	}

	// Convert db.GetUserByEmailRow to model.User
	fullNameStr := ""
	if dbUser.FullName.Valid {
		fullNameStr = dbUser.FullName.String
	}
	emailStr := ""
	if dbUser.Email.Valid {
		emailStr = dbUser.Email.String
	}

	return &model.User{
		ID:       fmt.Sprintf("%d", dbUser.ID), // Convert int64 to string for GraphQL ID
		FullName: &fullNameStr,
		Email:    &emailStr,
	}, nil
}

// CreateRole is the resolver for the createRole field.
func (r *mutationResolver) CreateRole(ctx context.Context, input model.NewRole) (*model.Role, error) {
	panic(fmt.Errorf("not implemented: CreateRole - createRole"))
}

// UpdateRole is the resolver for the updateRole field.
func (r *mutationResolver) UpdateRole(ctx context.Context, input model.UpdateRole) (*model.Role, error) {
	panic(fmt.Errorf("not implemented: UpdateRole - updateRole"))
}

// DeleteRole is the resolver for the deleteRole field.
func (r *mutationResolver) DeleteRole(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteRole - deleteRole"))
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context) ([]*model.Role, error) {
	panic(fmt.Errorf("not implemented: Roles - roles"))
}

// Role is the resolver for the role field.
func (r *queryResolver) Role(ctx context.Context, id string) (*model.Role, error) {
	panic(fmt.Errorf("not implemented: Role - role"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
