package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"crypto/rand"
	"fmt"
	"math/big"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/manojnegi/gql/db"
	"github.com/manojnegi/gql/graph/model"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	randNumber, _ := rand.Int(rand.Reader, big.NewInt(100))
	todo := &model.Todo{
		Text:   input.Text,
		ID:     fmt.Sprintf("T%d", randNumber),
		UserID: input.UserID,
	}
	r.todos = append(r.todos, todo)
	return todo, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	// Generate a unique ID for the user
	userID := uuid.New().String()

	// Combine first name and last name into full name
	fullName := input.Fname + " " + input.Lname

	// Prepare timestamp
	now := time.Now()
	timestamp := pgtype.Timestamp{
		Time:  now,
		Valid: true,
	}

	// Use sqlc to create user
	dbUser, err := r.queries.CreateUser(ctx, db.CreateUserParams{
		ID:        userID,
		Name:      fullName,
		Email:     pgtype.Text{String: input.Email, Valid: true},
		CreatedAt: timestamp,
		UpdatedAt: timestamp,
	})

	if err != nil {
		return nil, fmt.Errorf("failed to create user: %w", err)
	}

	// Convert db.User to model.User
	return &model.User{
		ID:   dbUser.ID,
		Name: dbUser.Name,
	}, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	return r.todos, nil
}

// User is the resolver for the user field.
func (r *todoResolver) User(ctx context.Context, obj *model.Todo) (*model.User, error) {
	return &model.User{ID: obj.UserID, Name: "user " + obj.UserID}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Todo returns TodoResolver implementation.
func (r *Resolver) Todo() TodoResolver { return &todoResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type todoResolver struct{ *Resolver }
