package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	"github.com/manojnegi/gql/db"
	"github.com/manojnegi/gql/graph/model"
	"github.com/manojnegi/gql/utils"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	params := db.CreateUserParams{
		Username:      input.Username,
		Email:         input.Email,
		Phone:         utils.PgTextFromPtr(input.Phone),
		PasswordHash:  input.Password,
		RoleID:        utils.PgUUIDFromPtr(input.RoleID),
		ProfessionID:  utils.PgUUIDFromPtr(input.ProfessionID),
		DisplayName:   utils.PgTextFromPtr(input.DisplayName),
		Bio:           utils.PgTextFromPtr(input.Bio),
		AvatarUrl:     utils.PgTextFromPtr(input.AvatarURL),
		CoverImageUrl: utils.PgTextFromPtr(input.CoverImageURL),
		CountryID:     utils.PgUUIDFromPtr(input.CountryID),
		TimezoneID:    utils.PgUUIDFromPtr(input.TimezoneID),
	}
	user, err := r.queries.CreateUser(ctx, params)
	if err != nil {
		return nil, err
	}
	return &model.User{
		ID:            utils.PgUUIDToUUID(user.ID),
		Username:      user.Username,
		Email:         user.Email,
		Phone:         utils.PgTextToPtr(user.Phone),
		RoleID:        utils.PgUUIDPtr(user.RoleID),
		ProfessionID:  utils.PgUUIDPtr(user.ProfessionID),
		DisplayName:   utils.PgTextToPtr(user.DisplayName),
		Bio:           utils.PgTextToPtr(user.Bio),
		AvatarURL:     utils.PgTextToPtr(user.AvatarUrl),
		CoverImageURL: utils.PgTextToPtr(user.CoverImageUrl),
		CountryID:     utils.PgUUIDPtr(user.CountryID),
		TimezoneID:    utils.PgUUIDPtr(user.TimezoneID),
	}, nil
}
