// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

type Country struct {
	ID           uuid.UUID `json:"id"`
	Code         string    `json:"code"`
	CodeAlpha3   string    `json:"codeAlpha3"`
	Name         string    `json:"name"`
	NativeName   *string   `json:"nativeName,omitempty"`
	PhoneCode    *string   `json:"phoneCode,omitempty"`
	CurrencyCode *string   `json:"currencyCode,omitempty"`
	FlagEmoji    *string   `json:"flagEmoji,omitempty"`
	IsActive     bool      `json:"isActive"`
	CreatedAt    *string   `json:"createdAt,omitempty"`
}

type CreateCountryInput struct {
	Code         string  `json:"code"`
	CodeAlpha3   string  `json:"codeAlpha3"`
	Name         string  `json:"name"`
	NativeName   *string `json:"nativeName,omitempty"`
	PhoneCode    *string `json:"phoneCode,omitempty"`
	CurrencyCode *string `json:"currencyCode,omitempty"`
	FlagEmoji    *string `json:"flagEmoji,omitempty"`
	IsActive     *bool   `json:"isActive,omitempty"`
}

type CreateUserInput struct {
	Username      string     `json:"username"`
	Email         string     `json:"email"`
	Phone         *string    `json:"phone,omitempty"`
	Password      string     `json:"password"`
	RoleID        *uuid.UUID `json:"roleId,omitempty"`
	ProfessionID  *uuid.UUID `json:"professionId,omitempty"`
	DisplayName   *string    `json:"displayName,omitempty"`
	Bio           *string    `json:"bio,omitempty"`
	AvatarURL     *string    `json:"avatarUrl,omitempty"`
	CoverImageURL *string    `json:"coverImageUrl,omitempty"`
	CountryID     *uuid.UUID `json:"countryId,omitempty"`
	TimezoneID    *uuid.UUID `json:"timezoneId,omitempty"`
}

type Mutation struct {
}

type NewRole struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type Query struct {
}

type Role struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type UpdateCountryInput struct {
	Code         *string `json:"code,omitempty"`
	CodeAlpha3   *string `json:"codeAlpha3,omitempty"`
	Name         *string `json:"name,omitempty"`
	NativeName   *string `json:"nativeName,omitempty"`
	PhoneCode    *string `json:"phoneCode,omitempty"`
	CurrencyCode *string `json:"currencyCode,omitempty"`
	FlagEmoji    *string `json:"flagEmoji,omitempty"`
	IsActive     *bool   `json:"isActive,omitempty"`
}

type UpdateRole struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

type User struct {
	ID                 uuid.UUID  `json:"id"`
	Username           string     `json:"username"`
	Email              string     `json:"email"`
	Phone              *string    `json:"phone,omitempty"`
	DisplayName        *string    `json:"displayName,omitempty"`
	Bio                *string    `json:"bio,omitempty"`
	AvatarURL          *string    `json:"avatarUrl,omitempty"`
	CoverImageURL      *string    `json:"coverImageUrl,omitempty"`
	IsVerified         bool       `json:"isVerified"`
	IsPrivate          bool       `json:"isPrivate"`
	FollowerCount      int32      `json:"followerCount"`
	FollowingCount     int32      `json:"followingCount"`
	TotalLikesReceived int32      `json:"totalLikesReceived"`
	TotalViews         int32      `json:"totalViews"`
	RoleID             *uuid.UUID `json:"roleId,omitempty"`
	ProfessionID       *uuid.UUID `json:"professionId,omitempty"`
	CountryID          *uuid.UUID `json:"countryId,omitempty"`
	TimezoneID         *uuid.UUID `json:"timezoneId,omitempty"`
}
