// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: countries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCountry = `-- name: CreateCountry :one
INSERT INTO countries (
  code,
  code_alpha3,
  name,
  native_name,
  phone_code,
  currency_code,
  flag_emoji,
  is_active
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, COALESCE($8, TRUE)
)
RETURNING id, code, code_alpha3, name, native_name, phone_code, currency_code, flag_emoji, is_active, created_at
`

type CreateCountryParams struct {
	Code         string      `json:"code"`
	CodeAlpha3   string      `json:"code_alpha3"`
	Name         string      `json:"name"`
	NativeName   pgtype.Text `json:"native_name"`
	PhoneCode    pgtype.Text `json:"phone_code"`
	CurrencyCode pgtype.Text `json:"currency_code"`
	FlagEmoji    pgtype.Text `json:"flag_emoji"`
	Column8      interface{} `json:"column_8"`
}

func (q *Queries) CreateCountry(ctx context.Context, arg CreateCountryParams) (Country, error) {
	row := q.db.QueryRow(ctx, createCountry,
		arg.Code,
		arg.CodeAlpha3,
		arg.Name,
		arg.NativeName,
		arg.PhoneCode,
		arg.CurrencyCode,
		arg.FlagEmoji,
		arg.Column8,
	)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CodeAlpha3,
		&i.Name,
		&i.NativeName,
		&i.PhoneCode,
		&i.CurrencyCode,
		&i.FlagEmoji,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateCountry = `-- name: DeactivateCountry :exec
UPDATE countries
SET is_active = FALSE
WHERE id = $1
`

func (q *Queries) DeactivateCountry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateCountry, id)
	return err
}

const getCountryByID = `-- name: GetCountryByID :one
SELECT id, code, code_alpha3, name, native_name, phone_code, currency_code, flag_emoji, is_active, created_at
FROM countries
WHERE id = $1
`

func (q *Queries) GetCountryByID(ctx context.Context, id pgtype.UUID) (Country, error) {
	row := q.db.QueryRow(ctx, getCountryByID, id)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CodeAlpha3,
		&i.Name,
		&i.NativeName,
		&i.PhoneCode,
		&i.CurrencyCode,
		&i.FlagEmoji,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listCountries = `-- name: ListCountries :many
SELECT id, code, code_alpha3, name, native_name, phone_code, currency_code, flag_emoji, is_active, created_at
FROM countries
WHERE is_active = TRUE
ORDER BY name
`

func (q *Queries) ListCountries(ctx context.Context) ([]Country, error) {
	rows, err := q.db.Query(ctx, listCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Country{}
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.CodeAlpha3,
			&i.Name,
			&i.NativeName,
			&i.PhoneCode,
			&i.CurrencyCode,
			&i.FlagEmoji,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCountry = `-- name: UpdateCountry :one
UPDATE countries
SET
  code = $2,
  code_alpha3 = $3,
  name = $4,
  native_name = $5,
  phone_code = $6,
  currency_code = $7,
  flag_emoji = $8,
  is_active = $9
WHERE id = $1
RETURNING id, code, code_alpha3, name, native_name, phone_code, currency_code, flag_emoji, is_active, created_at
`

type UpdateCountryParams struct {
	ID           pgtype.UUID `json:"id"`
	Code         string      `json:"code"`
	CodeAlpha3   string      `json:"code_alpha3"`
	Name         string      `json:"name"`
	NativeName   pgtype.Text `json:"native_name"`
	PhoneCode    pgtype.Text `json:"phone_code"`
	CurrencyCode pgtype.Text `json:"currency_code"`
	FlagEmoji    pgtype.Text `json:"flag_emoji"`
	IsActive     pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateCountry(ctx context.Context, arg UpdateCountryParams) (Country, error) {
	row := q.db.QueryRow(ctx, updateCountry,
		arg.ID,
		arg.Code,
		arg.CodeAlpha3,
		arg.Name,
		arg.NativeName,
		arg.PhoneCode,
		arg.CurrencyCode,
		arg.FlagEmoji,
		arg.IsActive,
	)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CodeAlpha3,
		&i.Name,
		&i.NativeName,
		&i.PhoneCode,
		&i.CurrencyCode,
		&i.FlagEmoji,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
