// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCountry(ctx context.Context, arg CreateCountryParams) (Country, error)
	DeactivateCountry(ctx context.Context, id pgtype.UUID) error
	GetCountryByID(ctx context.Context, id pgtype.UUID) (Country, error)
	ListCountries(ctx context.Context) ([]Country, error)
	UpdateCountry(ctx context.Context, arg UpdateCountryParams) (Country, error)
}

var _ Querier = (*Queries)(nil)
