// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    email,
    phone,
    password_hash,
    role_id,
    profession_id,
    display_name,
    bio,
    avatar_url,
    cover_image_url,
    is_verified,
    is_private,
    follower_count,
    following_count,
    total_likes_received,
    total_views,
    date_of_birth,
    country_id,
    timezone_id
)
VALUES (
    $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,
    $11,$12,$13,$14,$15,$16,$17,$18,$19
)
RETURNING
    id,
    username,
    email,
    phone,
    password_hash,
    role_id,
    profession_id,
    display_name,
    bio,
    avatar_url,
    cover_image_url,
    is_verified,
    is_private,
    follower_count,
    following_count,
    total_likes_received,
    total_views,
    date_of_birth,
    country_id,
    timezone_id,
    created_at,
    updated_at,
    last_login_at
`

type CreateUserParams struct {
	Username           string      `json:"username"`
	Email              string      `json:"email"`
	Phone              pgtype.Text `json:"phone"`
	PasswordHash       string      `json:"password_hash"`
	RoleID             pgtype.UUID `json:"role_id"`
	ProfessionID       pgtype.UUID `json:"profession_id"`
	DisplayName        pgtype.Text `json:"display_name"`
	Bio                pgtype.Text `json:"bio"`
	AvatarUrl          pgtype.Text `json:"avatar_url"`
	CoverImageUrl      pgtype.Text `json:"cover_image_url"`
	IsVerified         pgtype.Bool `json:"is_verified"`
	IsPrivate          pgtype.Bool `json:"is_private"`
	FollowerCount      pgtype.Int4 `json:"follower_count"`
	FollowingCount     pgtype.Int4 `json:"following_count"`
	TotalLikesReceived pgtype.Int8 `json:"total_likes_received"`
	TotalViews         pgtype.Int8 `json:"total_views"`
	DateOfBirth        pgtype.Date `json:"date_of_birth"`
	CountryID          pgtype.UUID `json:"country_id"`
	TimezoneID         pgtype.UUID `json:"timezone_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.RoleID,
		arg.ProfessionID,
		arg.DisplayName,
		arg.Bio,
		arg.AvatarUrl,
		arg.CoverImageUrl,
		arg.IsVerified,
		arg.IsPrivate,
		arg.FollowerCount,
		arg.FollowingCount,
		arg.TotalLikesReceived,
		arg.TotalViews,
		arg.DateOfBirth,
		arg.CountryID,
		arg.TimezoneID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.RoleID,
		&i.ProfessionID,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.CoverImageUrl,
		&i.IsVerified,
		&i.IsPrivate,
		&i.FollowerCount,
		&i.FollowingCount,
		&i.TotalLikesReceived,
		&i.TotalViews,
		&i.DateOfBirth,
		&i.CountryID,
		&i.TimezoneID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT
    id,
    username,
    email,
    phone,
    password_hash,
    role_id,
    profession_id,
    display_name,
    bio,
    avatar_url,
    cover_image_url,
    is_verified,
    is_private,
    follower_count,
    following_count,
    total_likes_received,
    total_views,
    date_of_birth,
    country_id,
    timezone_id,
    created_at,
    updated_at,
    last_login_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.RoleID,
		&i.ProfessionID,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.CoverImageUrl,
		&i.IsVerified,
		&i.IsPrivate,
		&i.FollowerCount,
		&i.FollowingCount,
		&i.TotalLikesReceived,
		&i.TotalViews,
		&i.DateOfBirth,
		&i.CountryID,
		&i.TimezoneID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
    id,
    username,
    email,
    password_hash,
    role_id,
    is_verified,
    created_at
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID           pgtype.UUID      `json:"id"`
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	RoleID       pgtype.UUID      `json:"role_id"`
	IsVerified   pgtype.Bool      `json:"is_verified"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.RoleID,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    id,
    username,
    display_name,
    avatar_url,
    follower_count,
    following_count,
    is_verified,
    created_at
FROM users
ORDER BY created_at DESC
`

type ListUsersRow struct {
	ID             pgtype.UUID      `json:"id"`
	Username       string           `json:"username"`
	DisplayName    pgtype.Text      `json:"display_name"`
	AvatarUrl      pgtype.Text      `json:"avatar_url"`
	FollowerCount  pgtype.Int4      `json:"follower_count"`
	FollowingCount pgtype.Int4      `json:"following_count"`
	IsVerified     pgtype.Bool      `json:"is_verified"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.FollowerCount,
			&i.FollowingCount,
			&i.IsVerified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    display_name = $2,
    bio = $3,
    avatar_url = $4,
    cover_image_url = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    username,
    display_name,
    bio,
    avatar_url,
    cover_image_url,
    updated_at
`

type UpdateUserParams struct {
	ID            pgtype.UUID `json:"id"`
	DisplayName   pgtype.Text `json:"display_name"`
	Bio           pgtype.Text `json:"bio"`
	AvatarUrl     pgtype.Text `json:"avatar_url"`
	CoverImageUrl pgtype.Text `json:"cover_image_url"`
}

type UpdateUserRow struct {
	ID            pgtype.UUID      `json:"id"`
	Username      string           `json:"username"`
	DisplayName   pgtype.Text      `json:"display_name"`
	Bio           pgtype.Text      `json:"bio"`
	AvatarUrl     pgtype.Text      `json:"avatar_url"`
	CoverImageUrl pgtype.Text      `json:"cover_image_url"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.DisplayName,
		arg.Bio,
		arg.AvatarUrl,
		arg.CoverImageUrl,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.CoverImageUrl,
		&i.UpdatedAt,
	)
	return i, err
}
