// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (full_name, username, email, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, full_name, username, email, password_hash, created_at
`

type CreateUserParams struct {
	FullName     pgtype.Text `json:"full_name"`
	Username     string      `json:"username"`
	Email        pgtype.Text `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

type CreateUserRow struct {
	ID           int64            `json:"id"`
	FullName     pgtype.Text      `json:"full_name"`
	Username     string           `json:"username"`
	Email        pgtype.Text      `json:"email"`
	PasswordHash pgtype.Text      `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FullName,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, username, email, password_hash, created_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           int64            `json:"id"`
	FullName     pgtype.Text      `json:"full_name"`
	Username     string           `json:"username"`
	Email        pgtype.Text      `json:"email"`
	PasswordHash pgtype.Text      `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, username, email, password_hash, created_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID           int64            `json:"id"`
	FullName     pgtype.Text      `json:"full_name"`
	Username     string           `json:"username"`
	Email        pgtype.Text      `json:"email"`
	PasswordHash pgtype.Text      `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, full_name, username, email, password_hash, created_at
FROM users
ORDER BY created_at DESC
`

type ListUsersRow struct {
	ID           int64            `json:"id"`
	FullName     pgtype.Text      `json:"full_name"`
	Username     string           `json:"username"`
	Email        pgtype.Text      `json:"email"`
	PasswordHash pgtype.Text      `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const signUpUser = `-- name: SignUpUser :one
INSERT INTO users (full_name, username, email, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, full_name, username, email, created_at
`

type SignUpUserParams struct {
	FullName     pgtype.Text `json:"full_name"`
	Username     string      `json:"username"`
	Email        pgtype.Text `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

type SignUpUserRow struct {
	ID        int64            `json:"id"`
	FullName  pgtype.Text      `json:"full_name"`
	Username  string           `json:"username"`
	Email     pgtype.Text      `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) SignUpUser(ctx context.Context, arg SignUpUserParams) (SignUpUserRow, error) {
	row := q.db.QueryRow(ctx, signUpUser,
		arg.FullName,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var i SignUpUserRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET full_name = $2, email = $3
WHERE id = $1
RETURNING id, full_name, username, email, password_hash, created_at
`

type UpdateUserParams struct {
	ID       int64       `json:"id"`
	FullName pgtype.Text `json:"full_name"`
	Email    pgtype.Text `json:"email"`
}

type UpdateUserRow struct {
	ID           int64            `json:"id"`
	FullName     pgtype.Text      `json:"full_name"`
	Username     string           `json:"username"`
	Email        pgtype.Text      `json:"email"`
	PasswordHash pgtype.Text      `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.FullName, arg.Email)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
